export { default as Switch } from './Switch/Switch.vue'
export { default as Button } from './Button/Button.vue'
export { default as Carousel } from './Carousel/Carousel.vue'
export { default as CarouselItem } from './Carousel/CarouselItem.vue'
export { default as Magnifier } from './Magnifier/Magnifier.vue'
export { default as Selector } from './Selector/Selector.vue'